name: Daily Commit

on:
  schedule:
    - cron: '15 01 * * *'  # Runs daily at 18:25 IST (12:55 UTC)

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: 22f3002277@ds.study.iitm.ac.in
        uses: actions/checkout@v2

      - name: Make changes
        run: |
          echo "Daily commit on $(date)" >> daily_commit.txt

      - name: Commit changes
        run: |
          git config --local user.email "22f3002277@ds.study.iitm.ac.in"
          git config --local user.name "brilo1819"
          git add daily_commit.txt
          git diff --cached --exit-code || git commit -m "Daily commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
