name: Daily Commit Workflow

on:
  schedule:
    - cron: '47 12 * * *'  

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit changes with email 22f3002277@ds.study.iitm.ac.in
        run: |
          echo "Daily commit" >> commit.txt
          git config --local user.email "22f3002277@ds.study.iitm.ac.in"
          git config --local user.name "Automated Commit"
          git add commit.txt
          git commit -m "Daily automated commit"
          git push origin main  # Change 'main' to your default branch if necessary
