name: Daily Commit

on:
  schedule:
    - cron: '05 01 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: 22f3002277@ds.study.iitm.ac.in
        uses: actions/checkout@v2

      - name: Make changes
        run: |
          echo "Daily commit on $(date)" >> daily_commit.txt

      - name: Commit changes
        run: |
          git config --local user.email "22f3002277@ds.study.iitm.ac.in"
          git config --local user.name "brilo1819"
          git add daily_commit.txt
          git commit -m "Daily commit"

      - name: Push changes
        run: git push origin main
